// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PaymentGateway.Application.Infrastructure;

namespace PaymentGateway.Application.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20201005194929_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("PaymentGateway.Data.Models.Card", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cvv")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryMonth")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("HolderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("cards");
                });
#pragma warning restore 612, 618
        }
    }
}
